micronaut:
  application:
    name: keyManager

datasources:
  default:
    url: ${DB_URI:`jdbc:postgresql://localhost:5432/postgres`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    schema-generate: CREATE_DROP
    dialect: ${DB_DIALECT:POSTGRES}

grpc:
  server:
    port: ${SERVER_PORT:50051}

jpa:
  default:
    properties:
      hibernate.hbm2ddl.auto: 'create-drop'
      hibernate.show_sql: true

# http cliente
endereco.client.itau: ${ITAU_URL:`http://localhost:9091`}
endereco.client.bcb: ${BCB_URL:`http://localhost:8082`}